### ISSUE TITLE
Menu items not list

### ISSUE THREAD

**Issue by keawade** [NathanBland/w-os#1]
Items in the application menu don't appear as a list. Instead they are all crammed in one line without spacing. 
![screenshot](https://cloud.githubusercontent.com/assets/7308850/17127004/db878d94-52c7-11e6-8002-fd4cfae313b6.PNG)

**Comment by keawade** [comment]
Also, the menu doesn't close on click away.

**Comment by NathanBland** [comment]
If you could open a `PR` with your calculator app, even if it doesn't work yet, I could get started at looking at this. The way it is now, I don't have anything other than my `textEditor` to work with.

**Comment by NathanBland** [comment]
- [x] Fix menu staying open after selecting an app
- [x] Fix menu staying open when clicked away from
- [x] Fix bad listing of components
