### ISSUE TITLE
Application titlebar default buttons

### ISSUE THREAD

**Issue by keawade** [NathanBland/w-os#2]
Should some of the buttons in the titlebar (eg `close`) be made default and be imported as a group? Seems that close should be on almost every window with the exact same functionality. Why make the app author figure out how to close the window?

**Comment by NathanBland** [comment]
`close` will soon be replaced by `new` for file `i/o` and other ops. It is not designed to close the app, but to reset it to its default state

**Comment by keawade** [comment]
Seems like you might want to call that `reset` or something then, haha. If I clicked a button labeled `new` and it cleared my app instead of opening another, I'd get kind of grumpy.

**Comment by NathanBland** [comment]
It very well could open up a new one.. I do need to make functionality for `diff`ing the contents of a file to see if they have changed though. Either way, these buttons aren't actually default, as they are injected on a per `app`/`component` basis and not part of the `wApp` wrapper. I'm closing this issue.
