### ISSUE TITLE
System Clock

### ISSUE THREAD

**Issue by keawade** [NathanBland/w-os#8]
## Core Feature Set
- [x] System tray display
- [ ] Time/Date formats
- [ ] Time zones

As always, let me know if you think of other enhancements or core features that should be included and I'll add them to the list.

**Comment by keawade** [comment]
I'm going to punt on the formats and time zones. I think those should be system settings eventually. For now, I've got a system tray clock that just goes off the browser's time.

**Comment by keawade** [comment]
We should keep this issue open to track those changes or move them to #13.

**Comment by NathanBland** [comment]
resolved by #21
